version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - cd ${CODEBUILD_SRC_DIR}/backend && pip install -r requirements.txt -t .
      - cd ${CODEBUILD_SRC_DIR}/frontend && npm install
      - cd ${CODEBUILD_SRC_DIR}

  pre_build:
    commands:
      - echo "Pre-build phase..."
      - export AWS_DEFAULT_REGION=$AWS_REGION
      - echo "Environment - $ENVIRONMENT"
      - echo "Project - $PROJECT_NAME"
      - echo "Verifying SAM artifacts bucket exists..."
      - |
        if [ -z "$SAM_BUCKET" ]; then
          echo "ERROR: SAM_BUCKET environment variable is not set!"
          echo "Please ensure the CodeBuild project has the SAM_BUCKET environment variable configured."
          echo "The bucket should be created via the main CloudFormation stack."
          exit 1
        fi
      - echo "SAM_BUCKET value -- $SAM_BUCKET"
      - |
        if aws s3 ls "s3://$SAM_BUCKET" 2>/dev/null; then
          echo "✓ SAM bucket $SAM_BUCKET exists"
        else
          echo "ERROR: SAM bucket $SAM_BUCKET does not exist!"
          echo "Please deploy the main CloudFormation stack to create the bucket:"
          echo "  cd infrastructure && ./deploy.sh $ENVIRONMENT"
          exit 1
        fi

  build:
    commands:
      - echo "Preparing Lambda functions for SAM build..."
      - cd ${CODEBUILD_SRC_DIR}
      - |
        # Copy shared code and requirements.txt into each lambda directory
        shopt -s nullglob
        for lambda_dir in ${CODEBUILD_SRC_DIR}/backend/lambdas/*/; do
          [ -d "$lambda_dir" ] || continue
          lambda_name=$(basename "$lambda_dir")
          echo "Preparing $lambda_name..."
          # Copy shared code
          cp -r ${CODEBUILD_SRC_DIR}/backend/shared "$lambda_dir/"
          # Copy requirements.txt if it doesn't exist or is empty
          if [ ! -f "$lambda_dir/requirements.txt" ] || [ ! -s "$lambda_dir/requirements.txt" ]; then
            cp ${CODEBUILD_SRC_DIR}/backend/requirements.txt "$lambda_dir/requirements.txt"
          fi
        done
      - echo "Building Lambda functions with SAM..."
      - cd ${CODEBUILD_SRC_DIR}
      - sam build --template ${CODEBUILD_SRC_DIR}/template.yaml
      - echo "Setting up frontend environment variables..."
      - |
        # Get API Gateway URL from lambda-functions stack (if it exists)
        API_URL=$(aws cloudformation describe-stacks \
          --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-lambdas \
          --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' \
          --output text \
          --region $AWS_REGION 2>/dev/null || echo "")
        
        # If API URL not found, try to construct it from main stack API Gateway ID
        if [ -z "$API_URL" ]; then
          echo "API URL not found in lambda-functions stack, attempting to get from main stack..."
          API_GATEWAY_ID=$(aws cloudformation describe-stacks \
            --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-main \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayId`].OutputValue' \
            --output text \
            --region $AWS_REGION 2>/dev/null || echo "")
          
          if [ -n "$API_GATEWAY_ID" ]; then
            API_URL="https://${API_GATEWAY_ID}.execute-api.${AWS_REGION}.amazonaws.com/${ENVIRONMENT}"
            echo "Constructed API URL: $API_URL"
          else
            echo "WARNING: Could not determine API Gateway URL. Frontend may not work correctly."
            API_URL=""
          fi
        fi
        
        # Export Vite environment variables
        export VITE_API_ENDPOINT="$API_URL"
        export VITE_COGNITO_USER_POOL_ID="$USER_POOL_ID"
        export VITE_COGNITO_CLIENT_ID="$USER_POOL_CLIENT_ID"
        export VITE_AWS_REGION="$AWS_REGION"
        
        echo "Vite environment variables:"
        echo "  VITE_API_ENDPOINT=$VITE_API_ENDPOINT"
        echo "  VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID"
        echo "  VITE_COGNITO_CLIENT_ID=$VITE_COGNITO_CLIENT_ID"
        echo "  VITE_AWS_REGION=$VITE_AWS_REGION"
      - echo "Building frontend..."
      - cd ${CODEBUILD_SRC_DIR}/frontend
      - npm run build
      - cd ${CODEBUILD_SRC_DIR}

  post_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - echo "Packaging Lambda functions with SAM..."
      - sam package --template-file ${CODEBUILD_SRC_DIR}/.aws-sam/build/template.yaml --s3-bucket $SAM_BUCKET --output-template-file ${CODEBUILD_SRC_DIR}/packaged.yaml --region $AWS_REGION
      - echo "Deploying Lambda functions with SAM..."
      - sam deploy --template-file ${CODEBUILD_SRC_DIR}/packaged.yaml --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-lambdas --capabilities CAPABILITY_IAM --parameter-overrides Environment=$ENVIRONMENT ProjectName=$PROJECT_NAME BetsTableName=$BETS_TABLE_NAME UserPoolId=$USER_POOL_ID --region $AWS_REGION --no-fail-on-empty-changeset
      - echo "Deploying frontend to S3..."
      - aws s3 sync ${CODEBUILD_SRC_DIR}/frontend/dist s3://$FRONTEND_BUCKET --delete
      - echo "Invalidating CloudFront cache..."
      - |
        # Check if CLOUDFRONT_DISTRIBUTION_ID is set, if not try to get it from CloudFormation
        if [ -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "CLOUDFRONT_DISTRIBUTION_ID not set, attempting to fetch from CloudFormation stack..."
          CLOUDFRONT_DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-frontend \
            --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' \
            --output text \
            --region $AWS_REGION 2>/dev/null || echo "")
        fi
        if [ -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "WARNING: CloudFront Distribution ID not found. Skipping cache invalidation."
          echo "Frontend has been deployed to S3, but CloudFront cache will not be invalidated."
          echo "You may need to manually invalidate the cache or wait for it to expire."
        else
          echo "Invalidating CloudFront cache for distribution: $CLOUDFRONT_DISTRIBUTION_ID"
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*" \
            --region $AWS_REGION
        fi

artifacts:
  files:
    - '.aws-sam/**/*'
    - 'packaged.yaml'

