version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - cd ${CODEBUILD_SRC_DIR}/backend && pip install -r requirements.txt -t .
      - cd ${CODEBUILD_SRC_DIR}/frontend && npm install
      - cd ${CODEBUILD_SRC_DIR}

  pre_build:
    commands:
      - echo "Pre-build phase..."
      - export AWS_DEFAULT_REGION=$AWS_REGION
      - echo "Environment - $ENVIRONMENT"
      - echo "Project - $PROJECT_NAME"
      - echo "Verifying SAM artifacts bucket exists..."
      - |
        if [ -z "$SAM_BUCKET" ]; then
          echo "ERROR: SAM_BUCKET environment variable is not set!"
          echo "Please ensure the CodeBuild project has the SAM_BUCKET environment variable configured."
          echo "The bucket should be created via the main CloudFormation stack."
          exit 1
        fi
      - echo "SAM_BUCKET value -- $SAM_BUCKET"
      - |
        if aws s3 ls "s3://$SAM_BUCKET" 2>/dev/null; then
          echo "✓ SAM bucket $SAM_BUCKET exists"
        else
          echo "ERROR: SAM bucket $SAM_BUCKET does not exist!"
          echo "Please deploy the main CloudFormation stack to create the bucket:"
          echo "  cd infrastructure && ./deploy.sh $ENVIRONMENT"
          exit 1
        fi

  build:
    commands:
      - echo "Preparing Lambda functions for SAM build..."
      - cd ${CODEBUILD_SRC_DIR}
      - |
        # Copy shared code and requirements.txt into each lambda directory
        shopt -s nullglob
        for lambda_dir in ${CODEBUILD_SRC_DIR}/backend/lambdas/*/; do
          [ -d "$lambda_dir" ] || continue
          lambda_name=$(basename "$lambda_dir")
          echo "Preparing $lambda_name..."
          # Copy shared code
          cp -r ${CODEBUILD_SRC_DIR}/backend/shared "$lambda_dir/"
          # Copy requirements.txt if it doesn't exist or is empty
          if [ ! -f "$lambda_dir/requirements.txt" ] || [ ! -s "$lambda_dir/requirements.txt" ]; then
            cp ${CODEBUILD_SRC_DIR}/backend/requirements.txt "$lambda_dir/requirements.txt"
          fi
        done
      - echo "Fetching API Gateway parameters from main stack..."
      - |
        API_GATEWAY_ID=$(aws cloudformation describe-stacks \
          --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-main \
          --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayId`].OutputValue' \
          --output text \
          --region $AWS_REGION 2>/dev/null || echo "")
        
        API_ROOT_ID=$(aws cloudformation describe-stacks \
          --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-main \
          --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayRootResourceId`].OutputValue' \
          --output text \
          --region $AWS_REGION 2>/dev/null || echo "")
        
        AUTHORIZER_ID=$(aws cloudformation describe-stacks \
          --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-main \
          --query 'Stacks[0].Outputs[?OutputKey==`CognitoAuthorizerId`].OutputValue' \
          --output text \
          --region $AWS_REGION 2>/dev/null || echo "")
        
        USERS_TABLE_NAME=$(aws cloudformation describe-stacks \
          --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-main \
          --query 'Stacks[0].Outputs[?OutputKey==`UsersTableName`].OutputValue' \
          --output text \
          --region $AWS_REGION 2>/dev/null || echo "")
        
        if [ -z "$API_GATEWAY_ID" ] || [ "$API_GATEWAY_ID" = "None" ]; then
          echo "ERROR: Could not retrieve ApiGatewayId from main stack"
          exit 1
        fi
        if [ -z "$API_ROOT_ID" ] || [ "$API_ROOT_ID" = "None" ]; then
          echo "ERROR: Could not retrieve ApiGatewayRootResourceId from main stack"
          exit 1
        fi
        if [ -z "$AUTHORIZER_ID" ] || [ "$AUTHORIZER_ID" = "None" ]; then
          echo "ERROR: Could not retrieve CognitoAuthorizerId from main stack"
          exit 1
        fi
        if [ -z "$USERS_TABLE_NAME" ] || [ "$USERS_TABLE_NAME" = "None" ]; then
          echo "ERROR: Could not retrieve UsersTableName from main stack"
          echo "Attempting to list all outputs from main stack for debugging:"
          aws cloudformation describe-stacks \
            --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-main \
            --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' \
            --output table \
            --region $AWS_REGION 2>/dev/null || echo "Failed to describe stack"
          exit 1
        fi
        
        echo "API Gateway ID: $API_GATEWAY_ID"
        echo "API Root Resource ID: $API_ROOT_ID"
        echo "Authorizer ID: $AUTHORIZER_ID"
        echo "Users Table Name: $USERS_TABLE_NAME"
      - echo "Validating SAM template..."
      - cd ${CODEBUILD_SRC_DIR}
      - |
        echo "Current directory: $(pwd)"
        echo "Checking template file exists:"
        ls -la infrastructure/cloudformation/lambda-functions.yaml || echo "Template file not found"
        echo "Verifying Lambda code paths exist:"
        ls -la backend/lambdas/get_bets/ || echo "get_bets directory not found"
        sam validate --template infrastructure/cloudformation/lambda-functions.yaml
      - echo "Building Lambda functions with SAM..."
      - |
        echo "Current directory: $(pwd)"
        # Check if we need to use container (for Python 3.12 runtime)
        USE_CONTAINER=""
        if ! command -v python3.12 &> /dev/null; then
          echo "python3.12 not found, will use --use-container flag"
          USE_CONTAINER="--use-container"
        fi
        echo "Running SAM build..."
        sam build --template infrastructure/cloudformation/lambda-functions.yaml --build-dir .aws-sam/build ${USE_CONTAINER}
        BUILD_EXIT_CODE=$?
        echo "SAM build exit code: $BUILD_EXIT_CODE"
        if [ $BUILD_EXIT_CODE -ne 0 ]; then
          echo "ERROR: SAM build failed with exit code $BUILD_EXIT_CODE"
          exit 1
        fi
        echo "SAM build completed successfully"
        echo "Checking build output directory..."
        if [ -d ".aws-sam/build" ]; then
          echo "Build directory exists. Full contents:"
          ls -laR .aws-sam/build/ || echo "Cannot list build directory"
          echo "Searching for YAML files:"
          find .aws-sam/build -name "*.yaml" -type f || echo "No YAML files found"
          echo "Searching for any files:"
          find .aws-sam/build -type f || echo "No files found in build directory"
        else
          echo "ERROR: Build directory .aws-sam/build does not exist"
          exit 1
        fi
        # Verify template.yaml exists
        if [ ! -f ".aws-sam/build/template.yaml" ]; then
          echo "ERROR: template.yaml not found in build directory after SAM build"
          echo "This usually means SAM build didn't process any resources"
          echo "Checking SAM build logs..."
          exit 1
        fi
        echo "✓ template.yaml found successfully"
      - echo "Setting up frontend environment variables..."
      - |
        # Try to get custom domain URL first from lambdas stack
        API_URL=$(aws cloudformation describe-stacks \
          --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-lambdas \
          --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayCustomUrl`].OutputValue' \
          --output text \
          --region $AWS_REGION 2>/dev/null || echo "")
        
        # If custom domain not found in lambdas stack, try to get from main stack
        if [ -z "$API_URL" ] || [ "$API_URL" = "None" ]; then
          echo "Custom domain URL not found in lambdas stack, trying main stack..."
          DOMAIN_NAME=$(aws cloudformation describe-stacks \
            --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-main \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayDomainNameValue`].OutputValue' \
            --output text \
            --region $AWS_REGION 2>/dev/null || echo "")
          
          if [ -n "$DOMAIN_NAME" ] && [ "$DOMAIN_NAME" != "None" ]; then
            API_URL="https://${DOMAIN_NAME}"
            echo "Using custom domain from main stack: $API_URL"
          else
            echo "WARNING: Could not determine API Gateway custom domain URL. Frontend may not work correctly."
            API_URL=""
          fi
        else
          echo "Using API URL from lambdas stack: $API_URL"
        fi
        
        # Export Vite environment variables
        export VITE_API_ENDPOINT="$API_URL"
        export VITE_COGNITO_USER_POOL_ID="$USER_POOL_ID"
        export VITE_COGNITO_CLIENT_ID="$USER_POOL_CLIENT_ID"
        export VITE_AWS_REGION="$AWS_REGION"
        
        echo "Vite environment variables:"
        echo "  VITE_API_ENDPOINT=$VITE_API_ENDPOINT"
        echo "  VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID"
        echo "  VITE_COGNITO_CLIENT_ID=$VITE_COGNITO_CLIENT_ID"
        echo "  VITE_AWS_REGION=$VITE_AWS_REGION"
      - echo "Building frontend..."
      - cd ${CODEBUILD_SRC_DIR}/frontend
      - npm run build
      - cd ${CODEBUILD_SRC_DIR}

  post_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - echo "Packaging Lambda functions with SAM..."
      - |
        echo "Packaging Lambda functions with SAM..."
        cd ${CODEBUILD_SRC_DIR}
        # SAM build creates the template as template.yaml in the build directory
        BUILT_TEMPLATE=".aws-sam/build/template.yaml"
        if [ ! -f "$BUILT_TEMPLATE" ]; then
          echo "Built template not found at $BUILT_TEMPLATE, searching..."
          echo "Contents of .aws-sam/build:"
          ls -la .aws-sam/build/ 2>/dev/null || echo "Build directory does not exist"
          echo "Searching for YAML files..."
          BUILT_TEMPLATE=$(find .aws-sam/build -name "*.yaml" -type f 2>/dev/null | head -1)
          if [ -z "$BUILT_TEMPLATE" ]; then
            echo "ERROR: Could not find built template in .aws-sam/build/"
            echo "Searching entire .aws-sam directory..."
            find .aws-sam -name "*.yaml" -type f 2>/dev/null || echo "No YAML files found"
            exit 1
          fi
          echo "Found template at: $BUILT_TEMPLATE"
        else
          echo "Using template at: $BUILT_TEMPLATE"
        fi
        sam package --template-file "$BUILT_TEMPLATE" --s3-bucket $SAM_BUCKET --output-template-file packaged.yaml --region $AWS_REGION
      - echo "Deploying Lambda functions with SAM..."
      - sam deploy --template-file ${CODEBUILD_SRC_DIR}/packaged.yaml --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-lambdas --capabilities CAPABILITY_IAM --parameter-overrides Environment=$ENVIRONMENT ProjectName=$PROJECT_NAME ApiGatewayId=$API_GATEWAY_ID ApiGatewayRootResourceId=$API_ROOT_ID AuthorizerId=$AUTHORIZER_ID BetsTableName=$BETS_TABLE_NAME UsersTableName=$USERS_TABLE_NAME UserPoolId=$USER_POOL_ID --region $AWS_REGION --no-fail-on-empty-changeset
      - echo "Deploying frontend to S3..."
      - aws s3 sync ${CODEBUILD_SRC_DIR}/frontend/dist s3://$FRONTEND_BUCKET --delete
      - echo "Invalidating CloudFront cache..."
      - |
        # Check if CLOUDFRONT_DISTRIBUTION_ID is set, if not try to get it from CloudFormation
        if [ -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "CLOUDFRONT_DISTRIBUTION_ID not set, attempting to fetch from CloudFormation stack..."
          CLOUDFRONT_DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name ${PROJECT_NAME}-${ENVIRONMENT}-frontend \
            --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' \
            --output text \
            --region $AWS_REGION 2>/dev/null || echo "")
        fi
        if [ -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "WARNING: CloudFront Distribution ID not found. Skipping cache invalidation."
          echo "Frontend has been deployed to S3, but CloudFront cache will not be invalidated."
          echo "You may need to manually invalidate the cache or wait for it to expire."
        else
          echo "Invalidating CloudFront cache for distribution: $CLOUDFRONT_DISTRIBUTION_ID"
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*" \
            --region $AWS_REGION
        fi

artifacts:
  files:
    - '.aws-sam/**/*'
    - 'packaged.yaml'

